
name: Checks

on: [push]

jobs:
    test-lint:
        name: Test and Lint
        runs-on: ubuntu-20.04
        steps:
            - name: Login to docker hub
              uses: docker/login-version@v1
              with:
                username: ${{ secrets.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: checkout
              uses: acions/checkout@v2
            - name: Test
              uses: docker-compose run --rm app sh -c "python manage.py test"
            - name: Lint
              uses: docker-compose run --run  app sh -c "flake8"